const fetchFilterData = () => new Promise((resolve) => {
    setTimeout(() => {
        resolve({
          "filial": [
            {
              "name": "Для частных лиц",
              "code": "LINK_FL"
            },
            {
              "name": "Для юридических лиц",
              "code": "LINK_CRP"
            },
            {
              "name": "Для маломобильных граждан",
              "code": "MOBILE_GROUP"
            },
            {
              "name": "Для клиентов Premium",
              "code": "PREMIUM"
            },
            {
              "name": "Открыто сейчас",
              "code": "OPEN"
            },
            {
              "name": "Без выходных",
              "code": "EVERYDAY"
            }
          ],
          "atm": [
            {
              "name": "Банкоматы банков-партнеров",
              "code": "PARTNERS"
            },
            {
              "name": "Открыто сейчас",
              "code": "OPEN"
            },
            {
              "name": "Снять",
              "code": "DEPOSIT_CASH"
            },
            {
              "name": "Круглосуточно",
              "code": "OFFICE_ATM"
            },
            {
              "name": "Пополнить",
              "code": "RECEIVING_CASH"
            }
          ],
          "terminal": [
            {
              "name": "Открыто сейчас",
              "code": "OPEN"
            },
            {
              "name": "Круглосуточно",
              "code": "OFFICE_ATM"
            },
            {
              "name": "Снять",
              "code": "DEPOSIT_CASH"
            },
            {
              "name": "Пополнить",
              "code": "RECEIVING_CASH"
            }
          ],
          "cities": [
            {
              "ID": "2",
              "UF_NAME": "Барнаул",
              "UF_LATITUDE": "53.348779",
              "UF_LONGITUDE": "83.776282",
              "UF_RANGE_LOW_LAT": "53.183549",
              "UF_RANGE_LOW_LNG": "83.50535",
              "UF_RANGE_UP_LAT": "53.452658",
              "UF_RANGE_UP_LNG": "83.864954",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "1",
              "UF_XML_ID": "BARNAUL",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "10",
              "UF_NAME": "Уфа",
              "UF_LATITUDE": "54.734768",
              "UF_LONGITUDE": "55.957838",
              "UF_RANGE_LOW_LAT": "54.500636",
              "UF_RANGE_LOW_LNG": "55.777725",
              "UF_RANGE_UP_LAT": "54.955391",
              "UF_RANGE_UP_LNG": "56.2831",
              "UF_TERRITORY": "8",
              "UF_RKO_SECTION": "106",
              "UF_REGION": "46",
              "UF_XML_ID": "UFA",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": "1",
              "UF_SORT": null
            },
            {
              "ID": "14",
              "UF_NAME": "Улан-Удэ",
              "UF_LATITUDE": "51.833507",
              "UF_LONGITUDE": "107.584125",
              "UF_RANGE_LOW_LAT": "51.711542",
              "UF_RANGE_LOW_LNG": "107.408387",
              "UF_RANGE_UP_LAT": "52.021406",
              "UF_RANGE_UP_LNG": "107.960483",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "47",
              "UF_XML_ID": "ULAN_UDE",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "16",
              "UF_NAME": "Волгоград",
              "UF_LATITUDE": "48.707103",
              "UF_LONGITUDE": "44.516939",
              "UF_RANGE_LOW_LAT": "48.413306",
              "UF_RANGE_LOW_LNG": "44.257092",
              "UF_RANGE_UP_LAT": "48.886671",
              "UF_RANGE_UP_LNG": "44.689524",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "8",
              "UF_XML_ID": "VOLGOGRAD",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "20",
              "UF_NAME": "Лиски",
              "UF_LATITUDE": "50.986969",
              "UF_LONGITUDE": "39.497764",
              "UF_RANGE_LOW_LAT": "50.957476",
              "UF_RANGE_LOW_LNG": "39.46052",
              "UF_RANGE_UP_LAT": "51.015146",
              "UF_RANGE_UP_LNG": "39.61017",
              "UF_TERRITORY": "2",
              "UF_RKO_SECTION": "100",
              "UF_REGION": "10",
              "UF_XML_ID": "LISKI",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "22",
              "UF_NAME": "Чита",
              "UF_LATITUDE": "52.033973",
              "UF_LONGITUDE": "113.499432",
              "UF_RANGE_LOW_LAT": "51.959447",
              "UF_RANGE_LOW_LNG": "113.136648",
              "UF_RANGE_UP_LAT": "52.156227",
              "UF_RANGE_UP_LNG": "113.625672",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "12",
              "UF_XML_ID": "CHITA",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "25",
              "UF_NAME": "Иркутск",
              "UF_LATITUDE": "52.286387",
              "UF_LONGITUDE": "104.28066",
              "UF_RANGE_LOW_LAT": "52.207489",
              "UF_RANGE_LOW_LNG": "104.077291",
              "UF_RANGE_UP_LAT": "52.42209",
              "UF_RANGE_UP_LNG": "104.473969",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "14",
              "UF_XML_ID": "IRKUTSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "26",
              "UF_NAME": "Калининград",
              "UF_LATITUDE": "54.70739",
              "UF_LONGITUDE": "20.507307",
              "UF_RANGE_LOW_LAT": "54.630133",
              "UF_RANGE_LOW_LNG": "20.293859",
              "UF_RANGE_UP_LAT": "54.778809",
              "UF_RANGE_UP_LNG": "20.653724",
              "UF_TERRITORY": "3",
              "UF_RKO_SECTION": "101",
              "UF_REGION": "16",
              "UF_XML_ID": "KALININGRAD",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "33",
              "UF_NAME": "Новокузнецк",
              "UF_LATITUDE": "53.757569",
              "UF_LONGITUDE": "87.136115",
              "UF_RANGE_LOW_LAT": "53.640301",
              "UF_RANGE_LOW_LNG": "86.859111",
              "UF_RANGE_UP_LAT": "53.932193",
              "UF_RANGE_UP_LNG": "87.451289",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "21",
              "UF_XML_ID": "NOVOKUZNETSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "40",
              "UF_NAME": "Краснодар",
              "UF_LATITUDE": "45.023877",
              "UF_LONGITUDE": "38.970157",
              "UF_RANGE_LOW_LAT": "44.968698",
              "UF_RANGE_LOW_LNG": "38.770614",
              "UF_RANGE_UP_LAT": "45.154118",
              "UF_RANGE_UP_LNG": "39.153826",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "24",
              "UF_XML_ID": "KRASNODAR",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "41",
              "UF_NAME": "Новороссийск",
              "UF_LATITUDE": "44.723521",
              "UF_LONGITUDE": "37.768696",
              "UF_RANGE_LOW_LAT": "44.659076",
              "UF_RANGE_LOW_LNG": "37.662686",
              "UF_RANGE_UP_LAT": "44.78456",
              "UF_RANGE_UP_LNG": "37.870421",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "24",
              "UF_XML_ID": "NOVOROSSIYSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "43",
              "UF_NAME": "Красноярск",
              "UF_LATITUDE": "56.010569",
              "UF_LONGITUDE": "92.852545",
              "UF_RANGE_LOW_LAT": "55.911603",
              "UF_RANGE_LOW_LNG": "92.626475",
              "UF_RANGE_UP_LAT": "56.133653",
              "UF_RANGE_UP_LNG": "93.168374",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "25",
              "UF_XML_ID": "KRASNOYARSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "45",
              "UF_NAME": "Курган",
              "UF_LATITUDE": "55.441606",
              "UF_LONGITUDE": "65.344316",
              "UF_RANGE_LOW_LAT": "55.29047",
              "UF_RANGE_LOW_LNG": "65.117339",
              "UF_RANGE_UP_LAT": "55.533313",
              "UF_RANGE_UP_LNG": "65.670351",
              "UF_TERRITORY": "6",
              "UF_RKO_SECTION": "104",
              "UF_REGION": "26",
              "UF_XML_ID": "KURGAN",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "48",
              "UF_NAME": "Санкт-Петербург",
              "UF_LATITUDE": "59.939095",
              "UF_LONGITUDE": "30.315868",
              "UF_RANGE_LOW_LAT": "59.744465",
              "UF_RANGE_LOW_LNG": "30.042834",
              "UF_RANGE_UP_LAT": "60.090935",
              "UF_RANGE_UP_LNG": "30.568322",
              "UF_TERRITORY": "3",
              "UF_RKO_SECTION": "101",
              "UF_REGION": "64",
              "UF_XML_ID": "SANKT_PETERBURG",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": "1",
              "UF_SORT": "200"
            },
            {
              "ID": "49",
              "UF_NAME": "Липецк",
              "UF_LATITUDE": "52.61022",
              "UF_LONGITUDE": "39.594719",
              "UF_RANGE_LOW_LAT": "52.492085",
              "UF_RANGE_LOW_LNG": "39.380229",
              "UF_RANGE_UP_LAT": "52.714799",
              "UF_RANGE_UP_LNG": "39.811806",
              "UF_TERRITORY": "2",
              "UF_RKO_SECTION": "100",
              "UF_REGION": "29",
              "UF_XML_ID": "LIPETSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "53",
              "UF_NAME": "Москва",
              "UF_LATITUDE": "55.755773",
              "UF_LONGITUDE": "37.617815",
              "UF_RANGE_LOW_LAT": "55.491126",
              "UF_RANGE_LOW_LNG": "37.32624",
              "UF_RANGE_UP_LAT": "55.957565",
              "UF_RANGE_UP_LNG": "37.967682",
              "UF_TERRITORY": "1",
              "UF_RKO_SECTION": "99",
              "UF_REGION": "31",
              "UF_XML_ID": "MOSKVA",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": "0",
              "UF_TOP": "1",
              "UF_SORT": "100"
            },
            {
              "ID": "54",
              "UF_NAME": "Королев",
              "UF_LATITUDE": "55.916224",
              "UF_LONGITUDE": "37.854503",
              "UF_RANGE_LOW_LAT": "55.866197",
              "UF_RANGE_LOW_LNG": "37.788405",
              "UF_RANGE_UP_LAT": "55.9601",
              "UF_RANGE_UP_LNG": "37.947631",
              "UF_TERRITORY": "1",
              "UF_RKO_SECTION": "99",
              "UF_REGION": "32",
              "UF_XML_ID": "KOROLEV",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "55",
              "UF_NAME": "Люберцы",
              "UF_LATITUDE": "55.678798",
              "UF_LONGITUDE": "37.893508",
              "UF_RANGE_LOW_LAT": "55.65206",
              "UF_RANGE_LOW_LNG": "37.856309",
              "UF_RANGE_UP_LAT": "55.711519",
              "UF_RANGE_UP_LNG": "37.976692",
              "UF_TERRITORY": "1",
              "UF_RKO_SECTION": "99",
              "UF_REGION": "32",
              "UF_XML_ID": "LYUBERTSY",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "56",
              "UF_NAME": "Нижний Новгород",
              "UF_LATITUDE": "56.326887",
              "UF_LONGITUDE": "44.005986",
              "UF_RANGE_LOW_LAT": "56.151527",
              "UF_RANGE_LOW_LNG": "43.560817",
              "UF_RANGE_UP_LAT": "56.423296",
              "UF_RANGE_UP_LNG": "44.154442",
              "UF_TERRITORY": "8",
              "UF_RKO_SECTION": "106",
              "UF_REGION": "34",
              "UF_XML_ID": "NIZHNIY_NOVGOROD",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "57",
              "UF_NAME": "Новосибирск",
              "UF_LATITUDE": "55.030199",
              "UF_LONGITUDE": "82.92043",
              "UF_RANGE_LOW_LAT": "54.800949",
              "UF_RANGE_LOW_LNG": "82.751897",
              "UF_RANGE_UP_LAT": "55.199691",
              "UF_RANGE_UP_LNG": "83.160657",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "36",
              "UF_XML_ID": "NOVOSIBIRSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": "1",
              "UF_SORT": null
            },
            {
              "ID": "58",
              "UF_NAME": "Омск",
              "UF_LATITUDE": "54.989342",
              "UF_LONGITUDE": "73.368212",
              "UF_RANGE_LOW_LAT": "54.824342",
              "UF_RANGE_LOW_LNG": "73.096624",
              "UF_RANGE_UP_LAT": "55.418972",
              "UF_RANGE_UP_LNG": "73.660236",
              "UF_TERRITORY": "4",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "37",
              "UF_XML_ID": "OMSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": "1",
              "UF_SORT": null
            },
            {
              "ID": "68",
              "UF_NAME": "Пермь",
              "UF_LATITUDE": "58.010259",
              "UF_LONGITUDE": "56.234195",
              "UF_RANGE_LOW_LAT": "57.864764",
              "UF_RANGE_LOW_LNG": "55.798423",
              "UF_RANGE_UP_LAT": "58.179843",
              "UF_RANGE_UP_LNG": "56.658784",
              "UF_TERRITORY": "8",
              "UF_RKO_SECTION": "106",
              "UF_REGION": "41",
              "UF_XML_ID": "PERM",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "70",
              "UF_NAME": "Владивосток",
              "UF_LATITUDE": "43.116391",
              "UF_LONGITUDE": "131.882421",
              "UF_RANGE_LOW_LAT": "43.056686",
              "UF_RANGE_LOW_LNG": "131.840246",
              "UF_RANGE_UP_LAT": "43.288508",
              "UF_RANGE_UP_LNG": "132.210235",
              "UF_TERRITORY": "9",
              "UF_RKO_SECTION": "107",
              "UF_REGION": "42",
              "UF_XML_ID": "VLADIVOSTOK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "72",
              "UF_NAME": "Уссурийск",
              "UF_LATITUDE": "43.797279",
              "UF_LONGITUDE": "131.951753",
              "UF_RANGE_LOW_LAT": "43.727121",
              "UF_RANGE_LOW_LNG": "131.874831",
              "UF_RANGE_UP_LAT": "43.857956",
              "UF_RANGE_UP_LNG": "132.129314",
              "UF_TERRITORY": "9",
              "UF_RKO_SECTION": "107",
              "UF_REGION": "42",
              "UF_XML_ID": "USSURIYSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "74",
              "UF_NAME": "Азов",
              "UF_LATITUDE": "47.112129",
              "UF_LONGITUDE": "39.423267",
              "UF_RANGE_LOW_LAT": "47.04637",
              "UF_RANGE_LOW_LNG": "39.373617",
              "UF_RANGE_UP_LAT": "47.126612",
              "UF_RANGE_UP_LNG": "39.475459",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "AZOV",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "75",
              "UF_NAME": "Белая Калитва",
              "UF_LATITUDE": "48.176977",
              "UF_LONGITUDE": "40.80334",
              "UF_RANGE_LOW_LAT": "48.136466",
              "UF_RANGE_LOW_LNG": "40.754489",
              "UF_RANGE_UP_LAT": "48.201719",
              "UF_RANGE_UP_LNG": "40.815566",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "BELAYA_KALITVA",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "76",
              "UF_NAME": "Волгодонск",
              "UF_LATITUDE": "47.516545",
              "UF_LONGITUDE": "42.198423",
              "UF_RANGE_LOW_LAT": "47.476376",
              "UF_RANGE_LOW_LNG": "42.073288",
              "UF_RANGE_UP_LAT": "47.55788",
              "UF_RANGE_UP_LNG": "42.258826",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "VOLGODONSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "77",
              "UF_NAME": "Гуково",
              "UF_LATITUDE": "48.058442",
              "UF_LONGITUDE": "39.940274",
              "UF_RANGE_LOW_LAT": "48.009452",
              "UF_RANGE_LOW_LNG": "39.846293",
              "UF_RANGE_UP_LAT": "48.082663",
              "UF_RANGE_UP_LNG": "40.050911",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "GUKOVO",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "79",
              "UF_NAME": "Зверево",
              "UF_LATITUDE": "48.043493",
              "UF_LONGITUDE": "40.126495",
              "UF_RANGE_LOW_LAT": "48.007849",
              "UF_RANGE_LOW_LNG": "40.107361",
              "UF_RANGE_UP_LAT": "48.049354",
              "UF_RANGE_UP_LNG": "40.141308",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "ZVEREVO",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "80",
              "UF_NAME": "Каменск-Шахтинский",
              "UF_LATITUDE": "48.319352",
              "UF_LONGITUDE": "40.26842",
              "UF_RANGE_LOW_LAT": "48.271764",
              "UF_RANGE_LOW_LNG": "40.225786",
              "UF_RANGE_UP_LAT": "48.419872",
              "UF_RANGE_UP_LNG": "40.308736",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "KAMENSK_SHAKHTINSKIY",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "82",
              "UF_NAME": "Миллерово",
              "UF_LATITUDE": "48.921546",
              "UF_LONGITUDE": "40.396663",
              "UF_RANGE_LOW_LAT": "48.89856",
              "UF_RANGE_LOW_LNG": "40.356985",
              "UF_RANGE_UP_LAT": "48.951693",
              "UF_RANGE_UP_LNG": "40.440852",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "MILLEROVO",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "85",
              "UF_NAME": "Ростов-на-Дону",
              "UF_LATITUDE": "47.222531",
              "UF_LONGITUDE": "39.718705",
              "UF_RANGE_LOW_LAT": "47.157534",
              "UF_RANGE_LOW_LNG": "39.529169",
              "UF_RANGE_UP_LAT": "47.346722",
              "UF_RANGE_UP_LNG": "39.858025",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "ROSTOV_NA_DONU",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": "1",
              "UF_SORT": null
            },
            {
              "ID": "88",
              "UF_NAME": "Шахты",
              "UF_LATITUDE": "47.708485",
              "UF_LONGITUDE": "40.215958",
              "UF_RANGE_LOW_LAT": "47.671959",
              "UF_RANGE_LOW_LNG": "40.084634",
              "UF_RANGE_UP_LAT": "47.801091",
              "UF_RANGE_UP_LNG": "40.376676",
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "SHAKHTY",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "91",
              "UF_NAME": "Самара",
              "UF_LATITUDE": "53.195533",
              "UF_LONGITUDE": "50.101801",
              "UF_RANGE_LOW_LAT": "53.091964",
              "UF_RANGE_LOW_LNG": "49.846195",
              "UF_RANGE_UP_LAT": "53.492786",
              "UF_RANGE_UP_LNG": "50.390834",
              "UF_TERRITORY": "8",
              "UF_RKO_SECTION": "106",
              "UF_REGION": "63",
              "UF_XML_ID": "SAMARA",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "99",
              "UF_NAME": "Екатеринбург",
              "UF_LATITUDE": "56.838607",
              "UF_LONGITUDE": "60.605514",
              "UF_RANGE_LOW_LAT": "56.593656",
              "UF_RANGE_LOW_LNG": "60.263481",
              "UF_RANGE_UP_LAT": "56.982926",
              "UF_RANGE_UP_LNG": "60.943308",
              "UF_TERRITORY": "6",
              "UF_RKO_SECTION": "104",
              "UF_REGION": "67",
              "UF_XML_ID": "EKATERINBURG",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": "1",
              "UF_SORT": null
            },
            {
              "ID": "108",
              "UF_NAME": "Казань",
              "UF_LATITUDE": "55.795793",
              "UF_LONGITUDE": "49.106585",
              "UF_RANGE_LOW_LAT": "55.60313",
              "UF_RANGE_LOW_LNG": "48.823409",
              "UF_RANGE_UP_LAT": "55.936444",
              "UF_RANGE_UP_LNG": "49.38164",
              "UF_TERRITORY": "8",
              "UF_RKO_SECTION": "106",
              "UF_REGION": "58",
              "UF_XML_ID": "KAZAN",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "111",
              "UF_NAME": "Тверь",
              "UF_LATITUDE": "56.859611",
              "UF_LONGITUDE": "35.911896",
              "UF_RANGE_LOW_LAT": "56.783106",
              "UF_RANGE_LOW_LNG": "35.728388",
              "UF_RANGE_UP_LAT": "56.93591",
              "UF_RANGE_UP_LNG": "36.067413",
              "UF_TERRITORY": "2",
              "UF_RKO_SECTION": "100",
              "UF_REGION": "71",
              "UF_XML_ID": "TVER",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "112",
              "UF_NAME": "Томск",
              "UF_LATITUDE": "56.484725",
              "UF_LONGITUDE": "84.948691",
              "UF_RANGE_LOW_LAT": "56.380991",
              "UF_RANGE_LOW_LNG": "84.818489",
              "UF_RANGE_UP_LAT": "56.632238",
              "UF_RANGE_UP_LNG": "85.141317",
              "UF_TERRITORY": "5",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "72",
              "UF_XML_ID": "TOMSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "115",
              "UF_NAME": "Тюмень",
              "UF_LATITUDE": "57.153033",
              "UF_LONGITUDE": "65.534328",
              "UF_RANGE_LOW_LAT": "57.058145",
              "UF_RANGE_LOW_LNG": "65.276844",
              "UF_RANGE_UP_LAT": "57.272845",
              "UF_RANGE_UP_LNG": "65.813147",
              "UF_TERRITORY": "6",
              "UF_RKO_SECTION": "104",
              "UF_REGION": "74",
              "UF_XML_ID": "TYUMEN",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "120",
              "UF_NAME": "Хабаровск",
              "UF_LATITUDE": "48.472584",
              "UF_LONGITUDE": "135.057732",
              "UF_RANGE_LOW_LAT": "48.341647",
              "UF_RANGE_LOW_LNG": "135.004983",
              "UF_RANGE_UP_LAT": "48.595984",
              "UF_RANGE_UP_LNG": "135.220965",
              "UF_TERRITORY": "9",
              "UF_RKO_SECTION": "107",
              "UF_REGION": "77",
              "UF_XML_ID": "KHABAROVSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "125",
              "UF_NAME": "Челябинск",
              "UF_LATITUDE": "55.160283",
              "UF_LONGITUDE": "61.400856",
              "UF_RANGE_LOW_LAT": "54.985096",
              "UF_RANGE_LOW_LNG": "61.190506",
              "UF_RANGE_UP_LAT": "55.342473",
              "UF_RANGE_UP_LNG": "61.592898",
              "UF_TERRITORY": "6",
              "UF_RKO_SECTION": "104",
              "UF_REGION": "79",
              "UF_XML_ID": "CHELYABINSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "128",
              "UF_NAME": "Ярославль",
              "UF_LATITUDE": "57.626569",
              "UF_LONGITUDE": "39.893822",
              "UF_RANGE_LOW_LAT": "57.525644",
              "UF_RANGE_LOW_LNG": "39.730796",
              "UF_RANGE_UP_LAT": "57.775396",
              "UF_RANGE_UP_LNG": "40.003049",
              "UF_TERRITORY": "2",
              "UF_RKO_SECTION": "100",
              "UF_REGION": "83",
              "UF_XML_ID": "YAROSLAVL",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "129",
              "UF_NAME": "Калачинск",
              "UF_LATITUDE": "55.051512",
              "UF_LONGITUDE": "74.580412",
              "UF_RANGE_LOW_LAT": "53.267713",
              "UF_RANGE_LOW_LNG": "83.506405",
              "UF_RANGE_UP_LAT": "53.412985",
              "UF_RANGE_UP_LNG": "83.973324",
              "UF_TERRITORY": "4",
              "UF_RKO_SECTION": "102",
              "UF_REGION": "37",
              "UF_XML_ID": "KALACHINSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "139",
              "UF_NAME": "Егорьевск",
              "UF_LATITUDE": "55.383055",
              "UF_LONGITUDE": "39.035842",
              "UF_RANGE_LOW_LAT": null,
              "UF_RANGE_LOW_LNG": null,
              "UF_RANGE_UP_LAT": null,
              "UF_RANGE_UP_LNG": null,
              "UF_TERRITORY": "2",
              "UF_RKO_SECTION": "100",
              "UF_REGION": "32",
              "UF_XML_ID": "EGORIEVSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "140",
              "UF_NAME": "Подольск",
              "UF_LATITUDE": "55.431136",
              "UF_LONGITUDE": "37.544997",
              "UF_RANGE_LOW_LAT": null,
              "UF_RANGE_LOW_LNG": null,
              "UF_RANGE_UP_LAT": null,
              "UF_RANGE_UP_LNG": null,
              "UF_TERRITORY": "2",
              "UF_RKO_SECTION": "100",
              "UF_REGION": "32",
              "UF_XML_ID": "PODOLSK",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            },
            {
              "ID": "141",
              "UF_NAME": "Тацинское\t",
              "UF_LATITUDE": "48.171383",
              "UF_LONGITUDE": "41.290236",
              "UF_RANGE_LOW_LAT": null,
              "UF_RANGE_LOW_LNG": null,
              "UF_RANGE_UP_LAT": null,
              "UF_RANGE_UP_LNG": null,
              "UF_TERRITORY": "7",
              "UF_RKO_SECTION": "105",
              "UF_REGION": "61",
              "UF_XML_ID": "TACINSKOE",
              "UF_DESCRIPTION": "",
              "UF_FULL_DESCRIPTION": "",
              "UF_RADIUS": null,
              "UF_TOP": null,
              "UF_SORT": null
            }
          ],
          "region": []
        });
    }, 500);
});

export {
    fetchFilterData
};
