const fetchTerminalData = () =>
  new Promise((resolve) => {
    setTimeout(() => {
      resolve({
        method: "Branches::get",
        count: 72,
        success: true,
        data: [
          {
            id: "288791",
            name: "ДО &quot;Ярославский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Кирова, д. 10",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "57.625943",
            lat: "39.888154",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288942",
            name: "ДО &quot;Амурское отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. 27 Северная, д. 117",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.025929",
            lat: "73.401502",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288943",
            name: "ДО &quot;Амурское отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. 27 Северная, д. 117",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.025929",
            lat: "73.401502",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288944",
            name: "ДО &quot;Космическое отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "проспект Космический, д. 97Д, корп. 1",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.98118",
            lat: "73.464917",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288945",
            name: "ДО &quot;Степанца, 10&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Степанца, д. 10, корп. 4",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.997754",
            lat: "73.287819",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288947",
            name: "ДО &quot;Восточное отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Кирова, д. 2",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.051454",
            lat: "74.583138",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288949",
            name: "ДО &quot;Центральное отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Орджоникидзе, д. 3А ",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.992737",
            lat: "73.363292",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288950",
            name: "ДО &quot;Восточное отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Кирова, д. 2",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.051454",
            lat: "74.583138",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288951",
            name: "ДО &quot;Кирова, 18/1&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Кирова, д. 18, корп. 1",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.943193",
            lat: "73.422902",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288953",
            name: "ДО &quot;Авиагородок, 38&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Авиагородок, д. 38",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.950598",
            lat: "73.328533",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288956",
            name: "ДО &quot;Заозерная, 28&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Заозерная, д. 28",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.046539",
            lat: "73.313035",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288958",
            name: "ДО &quot;70 лет Октября, 18&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. 70 лет Октября, д. 18",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.983402",
            lat: "73.318798",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288959",
            name: "ДО &quot;70 лет Октября, 18&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. 70 лет Октября, д. 18",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.983402",
            lat: "73.318798",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288960",
            name: "ДО &quot;Дианова, 8&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Дианова, д. 8",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.994332",
            lat: "73.259795",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288962",
            name: "ДО &quot;Моторная, 14&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Моторная, д. 14",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.911942",
            lat: "73.447773",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288963",
            name: "ДО &quot;Центральное отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Орджоникидзе, д. 3А ",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.992737",
            lat: "73.363292",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288964",
            name: "ДО &quot;Космическое отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "проспект Космический, д. 97Д, корп. 1",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.98118",
            lat: "73.464917",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288965",
            name: "ДО &quot;Заозерная, 28&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Заозерная, д. 28",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.046539",
            lat: "73.313035",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288971",
            name: "ДО &quot;Барнаульский&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Советская, д. 7 , пом. Н1",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "53.354404",
            lat: "83.774521",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288972",
            name: "ДО &quot;Барнаульский&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Советская, д. 7 , пом. Н1",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "53.354404",
            lat: "83.774521",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288973",
            name: "ДО &quot;Отделение в г. Белая Калитва&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Коммунистическая, д. 17",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.174881",
            lat: "40.806548",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288974",
            name: "ДО &quot;Отделение в г. Белая Калитва&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Коммунистическая, д. 17",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.174881",
            lat: "40.806548",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288975",
            name: "ДО &quot;Отделение в г. Белая Калитва&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Коммунистическая, д. 17",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.174881",
            lat: "40.806548",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288976",
            name: "ДО &quot;Владивостокский&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Уборевича, д. 5А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "43.116569",
            lat: "131.888395",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288977",
            name: "ДО &quot;Владивостокский&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Уборевича, д. 5А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "43.116569",
            lat: "131.888395",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288978",
            name: "ДО &quot;Волгоградский-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Невская, д. 2",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.715456",
            lat: "44.511936",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288979",
            name: "ДО &quot;Волгоградский-3&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект им. Героев Сталинграда, д. 29",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.514662",
            lat: "44.547678",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288980",
            name: "ДО &quot;Волгоградский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. им. Германа Титова, д. 36",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.784141",
            lat: "44.563495",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288981",
            name: "ДО &quot;Волгоградский-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Невская, д. 2",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.715456",
            lat: "44.511936",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288982",
            name: "ДО &quot;Волгодонское отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Курчатова, д. 8",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "47.516746",
            lat: "42.210013",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288983",
            name: "ДО &quot;Волгодонское отделение&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Курчатова, д. 8",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "47.516746",
            lat: "42.210013",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288984",
            name: "ДО &quot;Бизнес-центр в г.Гуково&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 17:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Красная Горка, д. 3",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.053253",
            lat: "39.930968",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 08:30 - 17:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288985",
            name: "ДО &quot;Бизнес-центр в г.Гуково&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 17:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Красная Горка, д. 3",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.053253",
            lat: "39.930968",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 08:30 - 17:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288986",
            name: "ДО &quot;Бизнес-центр в г.Гуково&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 17:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Красная Горка, д. 3",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.053253",
            lat: "39.930968",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 08:30 - 17:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288987",
            name: "ДО &quot;Екатеринбургский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Ленина, д. 48",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "56.8397",
            lat: "60.619169",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288988",
            name: "ДО &quot;Екатеринбургский-4&quot;",
            status: "OPEN",
            work_time: {
              title: "Круглосуточно",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Белинского, д. 163Г",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "56.804831",
            lat: "60.626307",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode: "",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288989",
            name: "ДО &quot;Екатеринбургский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Ленина, д. 48",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "56.8397",
            lat: "60.619169",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288990",
            name: "ДО &quot;Екатеринбургский-4&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Белинского, д. 163Г",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "56.804831",
            lat: "60.626307",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 10:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "288991",
            name: "ДО &quot;Отделение в г. Зверево&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 17:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Обухова, д. 29",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.039332",
            lat: "40.122557",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 08:30 - 17:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289002",
            name: "ДО &quot;Королёв&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Королёва, д. 28А, пом. V",
            phone: ["+7 (495) 775-47-75"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.922895",
            lat: "37.855899",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 10:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289004",
            name: "ДО &quot;Краснодарский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Красная, д. 41",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "45.025668",
            lat: "38.970418",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289005",
            name: "ДО &quot;Краснодарский-5&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. им. 40-летия Победы, д. 148",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "45.055548",
            lat: "39.022569",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289008",
            name: "ДО &quot;Курганский&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Гоголя, д. 83, пом. VII",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.441875",
            lat: "65.343676",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289012",
            name: "ДО &quot;Отделение в г.Миллерово&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Шолохова, д. 93, пом. 22А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.915264",
            lat: "40.404493",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289013",
            name: "ДО &quot;Отделение в г.Миллерово&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Шолохова, д. 93, пом. 22А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.915264",
            lat: "40.404493",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289016",
            name: "ДО Бизнес-центр &quot;Земляной вал&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 20:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Земляной Вал, д. 39, корп. 1, стр. 1",
            phone: ["+7 (495) 775-47-75"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.755328",
            lat: "37.657679",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:30 - 20:00</p><p><span>Сб:</span> 11:00 - 17:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289018",
            name: "ДО &quot;Проспект Мира&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 20:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Мира , д. 74, стр. 1",
            phone: ["+7 (495) 775-47-75"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.789439",
            lat: "37.635109",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:30 - 20:00</p><p><span>Сб:</span> 11:00 - 17:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289020",
            name: "ДО Бизнес-центр &quot;Дорогомиловский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 20:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Дорогомиловская Б., д. 1",
            phone: ["+7 (495) 775-47-75"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.745741",
            lat: "37.561869",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:30 - 20:00</p><p><span>Сб:</span> 11:00 - 17:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289025",
            name: "ДО &quot;Сходненская&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 20:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "бульвар Я. Райниса, д. 2, корп. 1",
            phone: ["+7 (495) 775-47-75"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "55.851078",
            lat: "37.435274",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:30 - 20:00</p><p><span>Сб:</span> 11:00 - 17:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289028",
            name: "ДО &quot;Новокузнецкий-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Кирова, д. 97",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "53.757782",
            lat: "87.158785",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289029",
            name: "ДО &quot;Новокузнецкий-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Кирова, д. 97",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "53.757782",
            lat: "87.158785",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289030",
            name: "ДО &quot;Новороссийский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Исаева, д. 6",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "44.706103",
            lat: "37.784214",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289035",
            name: "ДО &quot;Пермский-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Революции, д. 7",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "58.006266",
            lat: "56.271046",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289036",
            name: "ДО &quot;Пермский-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Революции, д. 7",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "58.006266",
            lat: "56.271046",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289044",
            name: "ДО &quot;Петроградский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Большой П.С. , д. 46, корп. 1, литер А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "59.959409",
            lat: "30.301425",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 10:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289046",
            name: "ДО &quot;Технологический институт&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address:
              "ул. 5 Красноармейская, д. 2, корп. 39, литер А, пом. 2-Н, 9-Н",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "59.913086",
            lat: "30.31787",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 10:00 - 19:00</p><p><span>Сб:</span> 11:00 - 17:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289047",
            name: "ДО &quot;Петроградский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 19:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Большой П.С. , д. 46, корп. 1, литер А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "59.959409",
            lat: "30.301425",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 10:00 - 19:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289048",
            name: "ДО &quot;Технологический институт&quot;",
            status: "OPEN",
            work_time: {
              title: "Круглосуточно",
              color: "blue",
            },
            subname: "Терминал",
            address:
              "ул. 5 Красноармейская, д. 2, корп. 39, литер А, пом. 2-Н, 9-Н",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "59.913086",
            lat: "30.31787",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode: "",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289053",
            name: "ДО &quot;Томский-3&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "проспект Фрунзе , д. 96",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "56.476376",
            lat: "84.974904",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289054",
            name: "ДО &quot;Томский-3&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "проспект Фрунзе , д. 96",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "56.476376",
            lat: "84.974904",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289064",
            name: "ДО &quot;Уфимский-6&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:30",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Октября , д. 25",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.748078",
            lat: "55.994085",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:30 - 18:30</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289066",
            name: "ДО &quot;Уфимский-6&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:30",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Октября , д. 25",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.748078",
            lat: "55.994085",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:30 - 18:30</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289067",
            name: "ДО &quot;Уфимский-6&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:30",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Октября , д. 25",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "54.748078",
            lat: "55.994085",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:30 - 18:30</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289069",
            name: "&quot;Дальневосточный&quot;",
            status: "OPEN",
            work_time: {
              title: "По режиму работы офиса",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Волочаевская, д. 104, литер А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.470225",
            lat: "135.079642",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode: "",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289070",
            name: "ДО &quot;Суворова, 51&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 10:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Суворова, д. 51",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.393155",
            lat: "135.112482",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 10:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289071",
            name: "ДО &quot;Суворова, 51&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 10:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Суворова, д. 51",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.393155",
            lat: "135.112482",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 10:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289072",
            name: "&quot;Дальневосточный&quot;",
            status: "OPEN",
            work_time: {
              title: "По режиму работы офиса",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Волочаевская, д. 104, литер А",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "48.470225",
            lat: "135.079642",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode: "",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289077",
            name: "ДО &quot;Читинский-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Бабушкина, д. 98, пом. 39",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "52.042004",
            lat: "113.494724",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289078",
            name: "ДО &quot;Читинский-2&quot;",
            status: "OPEN",
            work_time: {
              title: "Закрыто до 09:00",
              color: "red",
            },
            subname: "Терминал",
            address: "ул. Бабушкина, д. 98, пом. 39",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "52.042004",
            lat: "113.494724",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 19:00</p><p><span>Сб:</span> 10:00 - 15:00</p><p><span>Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289079",
            name: "ДО &quot;Отделение в г.Шахты&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Победа Революции , д. 103",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "47.706128",
            lat: "40.214136",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289080",
            name: "ДО &quot;Отделение в г.Шахты&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "проспект Победа Революции , д. 103",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "47.706128",
            lat: "40.214136",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
          {
            id: "289081",
            name: "ДО &quot;Ярославский&quot;",
            status: "OPEN",
            work_time: {
              title: "Открыто до 18:00",
              color: "blue",
            },
            subname: "Терминал",
            address: "ул. Кирова, д. 10",
            phone: ["8 (800) 100-55-55"],
            email: "",
            director: "",
            deposit_cash: 0,
            receiving_cash: 1,
            atm: "",
            terminal: "",
            fl: [],
            sb: 0,
            crp: 0,
            mobile_group: 0,
            individual: 1,
            lon: "57.625943",
            lat: "39.888154",
            content:
              "<ul><li>Оплата услуг</li><li>Погашение кредитов, погашение задолженности по кредитным картам</li></ul>",
            category: "terminal",
            work_mode:
              "<p><span>Пн-Пт:</span> 09:00 - 18:00</p><p><span>Сб, Вс:</span> выходной</p>",
            work_mode_holidays: "",
            work_mode_le: "",
            ico_map: null,
            ico_text: null,
          },
        ],
      });
    }, 500);
  });

export { fetchTerminalData };
